#!/bin/sh
#
# git-stash-ro
# Save snapshot of working tree into the stash without modifying working tree (aka read only).
# First argument (optional) is the stash message.
# Initially stolen from https://stackoverflow.com/questions/6315459/git-command-to-save-a-stash-without-modifying-working-tree

git stash
git stash apply